server:
  port: 8081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: students
          uri: lb://students-service
          predicates:
            - Path=/api/students/**
          filters:
            - StripPrefix=1
        - id: enrollments
          uri: lb://enrollments-service
          predicates:
            - Path=/api/enrollments/**
          filters:
            - StripPrefix=1
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
  main:
    web-application-type: reactive
    banner-mode: off

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO

gateway:
  api:
    key: skriveni-kljuc