server:
  port: 9082
spring:
  application:
    name: enrollments-service
  datasource:
    url: jdbc:h2:mem:enrolldb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    root: INFO
    com.example.enrollments.feign: DEBUG
    org.springframework.cloud.openfeign: INFO
    io.github.resilience4j: INFO

feign:
  client:
    config:
      default:
        loggerLevel: basic
resilience4j:
  circuitbreaker:
    instances:
      studentsCB:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
  retry:
    instances:
      studentsRetry:
        maxAttempts: 3
        waitDuration: 200ms


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka